### PR TITLE
Draft: feat(package): add vue integration

### PR DESCRIPTION
**Pull request by Sdju**
Hello!
I tried to add Vue integration for tma.
There are already:
- integration for tma
- eslint vue config
- tsconfig for vue
- docs page for vue

It isn't testted **at all**!! 
That's why I labeled PR as Draft

### CODE REVIEW

**Comment by heyqbnk** [comment]
Hey Denis! Thank you for your contribution!

> It isn't testted at all!!

Do you mean missing Vitest tests or you didn't try to use the code in the PR?

**Comment by Sdju** [comment]
I didn't try to use it in TG for now. I plan to check this next week. 
For now the PR is just the starting point

**Comment by heyqbnk** [comment]
Glad to hear it. Waiting for updates then!

**Comment by heyqbnk** [comment]
Closing due to inactivity. Feel free to return with this idea

**Pull request closed without merging**
